#! /usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2018 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
SCRIPT_FOLDER="$(dirname "$(readlink -f "${0}")")"

stop_daemon() {
  "${SCRIPT_FOLDER}/buildkitd" stop || :
}

build() {
  local image="${1}"
  local tag="${2}"
  local dockerfile="${3:-Dockerfile}"
  local context="${4:-"$(dirname "${dockerfile}")"}"

  "${SCRIPT_FOLDER}/bin/buildctl" build \
    --progress=plain \
    --frontend=dockerfile.v0 \
    --local context="${context}" \
    --local dockerfile="$(dirname "${dockerfile}")" \
    --opt filename="$(basename "${dockerfile}")" \
    --output type=docker,name="${image}:${tag}" \
    --export-cache type=inline | docker load
}

build_with_cache() {
  local image="${1}"
  local tag="${2}"
  local dockerfile="${3:-Dockerfile}"
  local context="${4:-"$(dirname "${dockerfile}")"}"

  "${SCRIPT_FOLDER}/bin/buildctl" build \
    --progress=plain \
    --frontend=dockerfile.v0 \
    --local context="${context}" \
    --local dockerfile="$(dirname "${dockerfile}")" \
    --opt filename="$(basename "${dockerfile}")" \
    --output type=docker,name="${image}:${tag}" \
    --export-cache type=inline \
    --import-cache type=registry,ref="${image}:${tag}" | docker load
}

prune() {
  "${SCRIPT_FOLDER}/bin/buildctl" prune \
    --keep-storage 10240
}

main() {
  echo "You must enter a valid command"
  exit 1
}

run() {
  local args=$*
  local f="${1:-}"

  if [[ "$f" == "" ]]; then
    main
  else
    trap stop_daemon EXIT
    if ! "${SCRIPT_FOLDER}/buildkitd" status 2> /dev/null; then
      "${SCRIPT_FOLDER}/buildkitd" start
    fi
    BUILDKIT_HOST="$("${SCRIPT_FOLDER}/buildkitd" host)"
    export BUILDKIT_HOST
    prune
    $args
  fi
}

run "$@"