#! /usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2018 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
SCRIPT_FOLDER="$(dirname "$(readlink -f "${0}")")"

BUILDKIT_VERSION="${BUILDKIT_VERSION:-latest}"
BUILDKIT_PORT="${BUILDKIT_PORT:-1234}"
BUILDKIT_VOLUMENAME="${BUILDKIT_VOLUMENAME:-buildkitd}"

export BUILDKIT_HOST="${BUILDKIT_HOST:-"tcp://0.0.0.0:${BUILDKIT_PORT}"}"

# Need docker
if ! command -v docker > /dev/null; then
  >&2 echo "ERROR: this program requires 'docker'"
  exit 1
fi

if [[ ! -x "${SCRIPT_FOLDER}/bin/buildctl" ]]; then
  if [[ $(uname) = "Darwin" ]]; then
    platform="darwin-amd64"
  else
    platform="linux-amd64"
  fi
  >&2 echo "INFO: Downloading buildkit (${BUILDKIT_VERSION}) binaries for platform ${platform}"
  releaseinfo=$(mktemp)
  if [[ "${BUILDKIT_VERSION}" = "latest" ]]; then
    curl -s "https://api.github.com/repos/moby/buildkit/releases/${BUILDKIT_VERSION}" > "${releaseinfo}"
  else
    curl -s "https://api.github.com/repos/moby/buildkit/releases/tags/${BUILDKIT_VERSION}" > "${releaseinfo}"
  fi
  buildkit_url="$(jq -r '.assets[] | select(.name | test("'${platform}'")) | .browser_download_url' "${releaseinfo}")"
  >&2 echo "INFO: Downloading ${buildkit_url}"
  curl -sL -o "${SCRIPT_FOLDER}/buildkit.tar.gz" "${buildkit_url}"
  tar -C "${SCRIPT_FOLDER}" -zxf "${SCRIPT_FOLDER}/buildkit.tar.gz"
  rm "${releaseinfo}"
fi

host() {
  echo "${BUILDKIT_HOST}"
}

status() {
  if "${SCRIPT_FOLDER}/bin/buildctl" du &> /dev/null; then
    >&2 echo "INFO: buildkitd is running"
    return 0
  else
    >&2 echo "INFO: buildkitd is not running"
    return 1
  fi
}

check_volume() {
  local ppid="${1}"
  if ! docker volume inspect "${BUILDKIT_VOLUMENAME}-${ppid}" &> /dev/null; then
    docker volume create "${BUILDKIT_VOLUMENAME}-${ppid}"
  fi
}

start() {
  local ppid="${1}"
  if ! status 2> /dev/null; then
    check_volume "${ppid}"
    docker pull "moby/buildkit:${BUILDKIT_VERSION}"
    docker run -d --privileged --rm -p "${BUILDKIT_PORT}:${BUILDKIT_PORT}" --mount source="${BUILDKIT_VOLUMENAME}-${ppid}",target=/var/lib/buildkit "moby/buildkit:${BUILDKIT_VERSION}" --addr "${BUILDKIT_HOST}" "$@"
  else 
    >&2 echo "WARNING: buildkitd is already running @ ${BUILDKIT_HOST}!"
  fi
}

stop() {
  local ppid="${1}"
  if status 2> /dev/null; then
    >&2 echo "INFO: stopping buildkitd @ ${BUILDKIT_HOST}"
    docker stop "$(docker ps -qf "publish=${BUILDKIT_PORT}")"
    >&2 echo "INFO: removing buildkitd volume ${BUILDKIT_VOLUMENAME}-${ppid}"
    docker volume rm -f "${BUILDKIT_VOLUMENAME}-${ppid}"
  else 
    >&2 echo "INFO: buildkitd is not running"
  fi
}

main() {
  echo "You must enter a valid command"
  exit 1
}

run() {
  local args=$*
  local f="${1:-}"

  if [[ "$f" == "" ]]; then
    main
  else
    $args
  fi
}

run "$@"