#! /usr/bin/env bash
#*******************************************************************************
# Copyright (c) 2018 Eclipse Foundation and others.
# This program and the accompanying materials are made available
# under the terms of the Eclipse Public License 2.0
# which is available at http://www.eclipse.org/legal/epl-v20.html,
# or the MIT License which is available at https://opensource.org/licenses/MIT.
# SPDX-License-Identifier: EPL-2.0 OR MIT
#*******************************************************************************
#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

IFS=$'\n\t'
SCRIPT_FOLDER="$(dirname $(readlink -f "${0}"))"

push() {
  local image="${1}"
  local tag="${2}"
  local retry="${3:-5}"

  n=0
  until [ $n -ge ${retry} ]; do
    docker push "${image}:${tag}" && break
    echo "Try #$n failed ($image:${tag})... sleeping for 15 seconds"
    n=$[$n+1]
    sleep 15
  done
}

digest() {
  local image="${1}"
  local tag="${2}"

  docker image list --no-trunc --format {{.ID}} "${image}${tag:+":${tag}"}"
}

push_if_changed() {
  local image="${1}"
  local tag="${2}"
  local dockerfile="${3}"

  local currentDigest="$(digest "${image}" "${tag}")"
  local cachedDigest="$(cat ${dockerfile}.digest || echo "<no_digest>")"
  if [[ "${currentDigest}" != "${cachedDigest}" ]]; then
    echo "INFO: pushing '${image}:${tag}' as it has been updated since the last time is has been pulled."
    push "${image}" "${tag}"
  else
    echo "INFO: No need to push '${image}:${tag}', it has same content as the last time is has been pulled."
  fi
}

build() {
  local image="${1}"
  local tag="${2}"
  local dockerfile="${3}"
  local context="${4:-"$(dirname "${dockerfile}")"}"

  if [[ $# -gt 4 ]]; then
    shift 4
  else
    shift $#
  fi

  docker pull "${image}:${tag}" || :
  
  digest "${image}" "${tag}" > "${dockerfile}.digest" || :

  if ${SCRIPT_FOLDER}/check-for-update.sh "${image}:${tag}"; then
    docker build --rm --pull --cache-from "${image}:${tag}" -t "${image}:${tag}" "$@" -f "${dockerfile}" "${context}"
  else
    docker build --rm --pull --no-cache -t "${image}:${tag}" -f "${dockerfile}" "$@" "${context}"
  fi
}

build_and_push() {
  local image="${1}"
  local tag="${2}"
  local dockerfile="${3}"
  local context="${4:-"$(dirname "${dockerfile}")"}"

  if [[ $# -gt 4 ]]; then
    shift 4
  else
    shift $#
  fi

  build "${image}" "${tag}" "${dockerfile}" "${context}" "$@"
  push "${image}" "${tag}"
}

build_all() {
  local repo="${1}"
  local from="${2}"
  local image="${3:-}"
  mapfile -t dockerfiles < <(find -L "${from}" -iname '*Dockerfile' | sed 's|\./||' | sort -V)
  for dockerfile in ${dockerfiles[@]}; do
    local build_dir=$(dirname "$dockerfile")
    local tag=${build_dir##*\/}
    : "${image:=$(basename "${from}")}"

    if [[ -z "${tag:-}" ]] || [[ "${tag}" == "$(basename "${from}")" ]]; then
      tag="latest"
    fi

    build "${repo}/${image}" "${tag}" "${dockerfile}"

    if [[ "${dockerfile}" = "${dockerfiles[-1]}" ]] && ! find "${from}" -type l -name "latest" | grep '.*'; then
      tag_alias "${repo}/${image}" "${tag}" "latest"
    fi
  done
}

push_all() {
  local repo="${1}"
  local from="${2}"
  local image="${3:-}"
  mapfile -t dockerfiles < <(find -L "${from}" -iname '*Dockerfile' | sed 's|\./||' | sort -V)
  for dockerfile in ${dockerfiles[@]}; do
    local build_dir=$(dirname "$dockerfile")
    local tag="${build_dir##*\/}"
    : "${image:=$(basename "${from}")}"

    if [[ -z "${tag:-}" ]] || [[ "${tag}" == "$(basename "${from}")" ]]; then
      tag="latest"
    fi
    
    push_if_changed "${repo}/${image}" "${tag}" "${dockerfile}"
    
    if [[ "${dockerfile}" = "${dockerfiles[-1]}" ]] && ! find "${from}" -type l -name "latest" | grep '.*'; then
      push_if_changed "${repo}/${image}" "latest" "${dockerfile}"
    fi
  done
}

tag_alias() {
  local image="${1}"
  local tag="${2}"
  local newtag="${3}"
  docker tag "${image}:${tag}" "${image}:${newtag}"
}

clean() {
  docker container prune -f
  docker image prune -f
  docker volume prune -f
}

rmi_all() {
  local r="${1}"
  if [[ $(docker image list ${r} | wc -l) -gt 1 ]]; then
    docker image list ${r} | tr -s ' ' | tail -n +2 | cut -d ' ' -f 3 | sort -u | xargs docker image rm -f
  fi
}

main() {
  echo "You must enter a valid command"
  exit 1
}

run() {
  local args=$*
  local f="${1:-}"

  if [[ "$f" == "" ]]; then
    main
  else
    $args
  fi
}

run "$@"